export const enum Paths {
  Startup = 'startup',
  Login = 'login',
  Signup = 'signup',
  Forgot = 'forgot',
  OTP = 'otp',
  ChangePassword = 'changepassword',
  Tabs = 'bottomtabs',
  Home = 'home',
  Products = 'products',
  HomeStack = 'Home',
  CartStack = 'Cart',
  Cart = 'cart',
  Checkout = 'checkout',
  Payment = 'payment',
  ProfileStack = 'Profile',
  Profile = 'profile',
  Settings = 'settings',
  Orders = 'orders',
  OrderDetails = 'orderdetail',
  WalletDetails = 'walletdetails',
  Subscriptions = 'subscriptions',
  SubscriptionsDetails = 'subscriptionsdetails',
  CreateSubscription = 'createsubscription',
  ChatStack = 'chatstack',
  ChatList = 'chatlist',
  Chat = 'chat',
}
