export const enum Paths {
  Example = 'example',
  Startup = 'startup',
  Login = 'login',
  Signup = 'signup',
  ForgotPassword = 'forgotPassword',
  OTP = 'OTP',
  ChangePassword = 'changePassword',
  WalletDetails = 'walletDetails',
  ChatList = 'chatlist',
  Chat = 'chat',
  Tabs = 'tabs',
  AdminTabs = 'admintabs',
}

export const enum TabPaths {
  Home = 'home',
  Profile = 'profile',
  Products = 'products',
  AddProduct = 'addProduct',
  ProductDetails = 'productDetails',
  CreateAd = 'createAd',
  AdPerformance = 'adPerformance',
  Orders = 'orders',
  OrderDetails = 'orderDetails',
  HomeStack = 'homeStack',
  ProfileStack = 'profileStack',
  ChatStack = 'chatstack',
  Analytics = 'analytics',
}

export const enum AdminPaths {
  AdminDashboard = 'admindashboard',
  VendorRequests = 'vendorRequests',
  VerifiedVendors = 'verifiedVendors',
  VendorDetails = 'vendorDetails',
  VendorApproval = 'vendorApproval',
  AdminDashboardStack = 'admindashboardstack',
  VendorProducts = 'vendorProducts',
  VendorProductView = 'vendorProductView',
  VendorOrderList = 'vendorOrderList',
  vendorSubcriptionList = 'vendorSubcriptionList',
  vendorAdList = 'vendorAdList',
  vendorWalletTransactions = 'vendorWalletTransactions',
  Certificate = 'certificate',
  UserList = 'userList',
  UserDetails = 'userDetails',
  UserOrders = 'userOrders',
  UserSubscriptions = 'userSubscriptions',
  UserTransactions = 'userTransactions',
  DeletedUsers = 'deletedUsers',
  DeletedVendors = 'deletedVendors',
  DisputeStack = 'disputestack',
  DisputeList = 'disputelist',
}
